---

- name: update server
  apt: update_cache=yes upgrade=dist cache_valid_time=3600

- name: install dependencies
  apt: name={{ dependencies }} state=latest

- name: install packages
  apt: name={{ packages|default([]) }} state=latest
