---

- name: install nginx
  apt: pkg=nginx state=latest

- name: remove default site
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify:
    - restart nginx

- name: create domain host
  template:
    src: nginx/sites-enabled/{{ domain }}.conf.j2
    dest: /etc/nginx/sites-enabled/{{ domain }}.conf
  notify:
    - restart nginx

- name: nginx service state
  service: name=nginx state=started enabled=yes

- name: append user to www-data
  user: name={{ user }} groups=www-data append=yes state=present
