imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

parameters:
    project:
        name:        argonbook
        version:     0.13

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enabled: true, enable_annotations: false }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: false

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        form_csrf_provider: "@form.csrf_provider"
        project:            "%project%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        ['ArgonGameBundle']
    java:           "/usr/bin/java"
    filters:
        less:
            bin:        "/usr/bin/less"
            apply_to:   "\\.less$"
            node_paths: ["/usr/local/lib/node_modules", "/usr/lib/node_modules/"]
        cssrewrite: ~
        closure:
            jar: "%kernel.root_dir%/../vendor/google/closure-compiler/compiler.jar"
        yui_css:
            jar: "%kernel.root_dir%/../vendor/yahoo/yuicompressor/yuicompressor-2.4.8.jar"
    assets:
        jqueryui-js:
            inputs: ["%kernel.root_dir%/../vendor/jquery/jqueryui/ui/jquery-ui.js"]
            output: js/jqueryui.js
        jqueryui-css:
            inputs: ["%kernel.root_dir%/../vendor/jquery/jqueryui/themes/base/*"]
            output: css/jqueryui.css
            filters: [cssrewrite]

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        mappings:
            gedmo_translatable:
                type:       annotation
                dir:        "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                prefix:     Gedmo\Translatable\Entity
                is_bundle:  false
            gedmo_tree:
                type:       annotation
                dir:        "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                prefix:     Gedmo\Tree\Entity
                is_bundle:  false

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Doctrine Extensions Configuration
stof_doctrine_extensions:
    default_locale: "%locale%"
    orm:
        default:
            sluggable:      true
            translatable:   true
            tree:           true
            timestampable:  true

# Locale Configuration
lunetics_locale:
    allowed_locales:        [de, en]
    guessing_order:         [query, cookie, session]
    cookie:
        set_on_change:      true
    form:
        languages_only:     true
    switcher:
        show_current_locale: true

# Bootstrap Configuration
braincrafted_bootstrap:
    auto_configure:
        knp_menu: false
    customize:
        variables_file: "%kernel.root_dir%/Resources/less/variables.less"
    less_filter: less

# FOSUser Configuration
fos_user:
    db_driver:     orm
    firewall_name: main
    user_class:    Argon\CommonBundle\Entity\Player

# FOSMessage
fos_message:
    db_driver:     orm
    thread_class:  Argon\MessageBundle\Entity\Thread
    message_class: Argon\MessageBundle\Entity\Message
    new_thread_form:
        type: argon_message.form.new_thread
