_argon_web:
    resource: "@ArgonWebBundle/Resources/config/routing/pages.xml"

_argon_blog:
    resource: "@ArgonBlogBundle/Resources/config/routing/blog.xml"

_argon_game_game:
    resource: "@ArgonGameBundle/Resources/config/routing/game.xml"

_argon_game_character:
    resource: "@ArgonGameBundle/Resources/config/routing/character.xml"

_argon_game_friendlist:
    resource: "@ArgonGameBundle/Resources/config/routing/friendlist.xml"

_argon_game_messenger:
    resource: "@ArgonGameBundle/Resources/config/routing/messenger.xml"

# ADMIN
_argon_web_admin:
    resource: "@ArgonWebBundle/Resources/config/routing/admin.xml"
    prefix: /admin

_argon_user_admin:
    resource: "@ArgonUserBundle/Resources/config/routing/admin.xml"
    prefix: /admin

_argon_blog_admin:
    resource: "@ArgonBlogBundle/Resources/config/routing/admin.xml"
    prefix: /admin

_argon_game_admin:
    resource: "@ArgonGameBundle/Resources/config/routing/admin.xml"
    prefix: /admin

# FOSUserBundle
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
