# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
        argon_game_character:
            id: argon_game.security.character_provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(error|profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true

            switch_user:
                provider:  argon_game_character
                parameter: _switch
                role:      ROLE_ALLOWED_TO_SWITCH_CHARACTER

    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm: bcrypt
            cost: 12
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_PJ:          []
        ROLE_PLAYER:      [ROLE_ALLOWED_TO_SWITCH_CHARACTER]
        ROLE_USER:        [ROLE_PLAYER]
        ROLE_DIRECTOR:    [ROLE_USER]
        ROLE_GAMEMASTER:  [ROLE_USER, ROLE_DIRECTOR]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_DIRECTOR, ROLE_GAMEMASTER, ROLE_ALLOWED_TO_SWITCH]

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET] }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/characters$, role: ROLE_PLAYER, methods: [GET] }
        - { path: ^/character/[-\w]+\:[-\w]+/, role: ROLE_PLAYER }
        - { path: ^/new, role: ROLE_PLAYER }
        - { path: ^/admin, roles: ROLE_SUPER_ADMIN }
