security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_CHARACTER:   []
        ROLE_USER:        [ROLE_ALLOWED_TO_SWITCH_CHARACTER]
        ROLE_DIRECTOR:    [ROLE_USER]
        ROLE_ADMIN:       [ROLE_USER, ROLE_DIRECTOR]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_DIRECTOR, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
        argon_game_character:
            id: argon_game.security.character_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            form_login:
                provider:      fos_userbundle
                csrf_provider: form.csrf_provider
            logout:     ~
            anonymous:  ~
            switch_user:
                provider:      argon_game_character
                parameter:     _switch
                role:          ROLE_ALLOWED_TO_SWITCH_CHARACTER

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/event, roles: ROLE_DIRECTOR }
        - { path: ^/inbox, roles: ROLE_CHARACTER }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
