---

- hosts: all
  become: yes
  roles:
    - { role: common }

- hosts: db
  become: yes
  roles:
    - { role: db }

- hosts: web
  become: yes
  roles:
    - { role: php }
    - { role: httpd }

- hosts: build
  become: yes
  roles:
    - { role: build }
