---

- hosts: all
  roles:
    - { role: ubuntu, become: yes }

- hosts: db
  roles:
    - { role: db, become: yes }

- hosts: web
  roles:
    - { role: php, become: yes }
    - { role: httpd, become: yes }
