---

- name: add repository key for debian
  when: ansible_distribution == 'Debian'
  apt_key: url=https://packages.sury.org/php/apt.gpg state=present

- name: add repository for debian
  when: ansible_distribution == 'Debian'
  apt_repository:
    repo: "deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
    update_cache: yes
    state: present

- name: add repository for ubuntu
  when: ansible_distribution == 'Ubuntu'
  apt_repository: repo=ppa:ondrej/php update_cache=yes state=present

- name: install php
  apt: name={{ php_packages|union([php_fpm_package] if php_fpm|bool else []) }} state=latest

- name: conf.d
  file: path=/etc/php/{{ php_version }}/conf.d mode=0755 state=directory

- name: configure
  template:
    src: php/php.ini.j2
    dest: /etc/php/{{ php_version }}/conf.d/90-custom.ini
    mode: 0644
  register: php_configured

- name: configuration link
  ignore_errors: yes # when conf.d is symlinked
  with_items: "{{ ['cli']|union(['fpm'] if php_fpm|bool else []) }}"
  file:
    src: /etc/php/{{ php_version }}/conf.d/90-custom.ini
    dest: /etc/php/{{ php_version }}/{{ item }}/conf.d/90-custom.ini
    state: link

- name: run php-fpm as normal user
  when: php_fpm|bool
  with_dict:
    user: "{{ user }}"
    group: www-data
  lineinfile:
    dest: /etc/php/{{ php_version }}/fpm/pool.d/www.conf
    regexp: "^{{ item.key }}"
    line: "{{ item.key }} = {{ item.value }}"
    state: present
  notify:
    - restart php-fpm

- name: php-fpm service state
  when: php_fpm|bool
  service: name=php{{ php_version }}-fpm state=started enabled=yes

- name: restart php-fpm when configured
  when: php_fpm|bool and php_configured.changed
  service: name=php{{ php_version }}-fpm state=restarted
