---

- name: add PHP repository
  apt_repository: repo=ppa:ondrej/php5 update_cache=yes state=present

- name: install php
  apt: pkg={{ item }} state=latest
  with_items:
    - php5-common
    - php5-cli
    - php5-intl
    - php5-sqlite
    - php5-fpm
    - php5-curl

- name: conf.d
  file: path=/etc/php5/conf.d mode=0755 state=directory
  become: yes

- name: configure
  template:
    src: php5/php.ini.j2
    dest: /etc/php5/conf.d/90-custom.ini
    mode: 0644
  notify:
    - restart fastcgi

- name: configuration link
  with_items: [cli, fpm]
  file:
    src: /etc/php5/conf.d/90-custom.ini
    dest: /etc/php5/{{ item }}/conf.d/90-custom.ini
    state: link

- name: php5-fpm service state
  service: name=php5-fpm state=started enabled=yes

- name: install composer
  shell: curl -sS https://getcomposer.org/installer | \
         php -- --install-dir=/usr/local/bin --filename=composer.phar
  args:
    creates: /usr/local/bin/composer.phar

- name: install phpdev tools
  when: phpdev is defined and phpdev|bool
  with_dict: "{{ phpdev_tools }}"
  get_url: url={{ item.value }} dest=/usr/local/bin/{{ item.key }}.phar mode=0755
