---

- name: add repository key for debian
  when: ansible_distribution == 'Debian'
  apt_key: url=https://packages.sury.org/php/apt.gpg state=present

- name: add repository for debian
  when: ansible_distribution == 'Debian'
  apt_repository:
    repo: "deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
    update_cache: yes
    state: present

- name: add repository for ubuntu
  when: ansible_distribution == 'Ubuntu'
  apt_repository: repo=ppa:ondrej/php update_cache=yes state=present

- name: install php
  with_items: "{{ php_packages|union([php_fpm_package] if php_fpm|bool else []) }}"
  apt: name={{ item }} state=latest

- name: conf.d
  file: path=/etc/php5/conf.d mode=0755 state=directory

- name: configure
  template:
    src: php5/php.ini.j2
    dest: /etc/php5/conf.d/90-custom.ini
    mode: 0644
  register: php_configured

- name: configuration link
  with_items: "{{ ['cli']|union(['fpm'] if php_fpm|bool else []) }}"
  file:
    src: /etc/php5/conf.d/90-custom.ini
    dest: /etc/php5/{{ item }}/conf.d/90-custom.ini
    state: link

- name: run php5-fpm as normal user
  when: php_fpm|bool
  with_dict:
    user: "{{ user }}"
    group: www-data
  lineinfile:
    dest: /etc/php5/fpm/pool.d/www.conf
    regexp: "^{{ item.key }}"
    line: "{{ item.key }} = {{ item.value }}"
    state: present
  notify:
    - restart php5-fpm

- name: php5-fpm service state
  when: php_fpm|bool
  service: name=php5-fpm state=started enabled=yes

- name: restart php5-fpm when configured
  when: php_fpm|bool and php_configured
  service: name=php5-fpm state=restarted
