---

- name: install requirements
  apt: name=python-mysqldb state=latest

- name: install mysql
  with_items:
    - mysql-server
    - mysql-client
  apt: name={{ item }} state=latest

- name: configure
  template:
    src: mysql/my.cnf.j2
    dest: /etc/mysql/conf.d/90-custom.cnf
    mode: 0644
  notify:
    - restart mysql

- name: mysql service state
  service: name=mysql state=started enabled=yes

- name: create db
  when: db is defined
  mysql_db: name={{ db }} state=present
