---

dependencies:
  - curl
  - software-properties-common
  - python-software-properties
  - python-setuptools
  - python-pip
  - python-apt
  - python-pycurl
  - apt-transport-https
  - ca-certificates
